### ISSUE TITLE
Web links for Marquise Technologies' solutions are outdated

### ISSUE THREAD

**Issue by laurencestoll** [4lm/amazing-digital-cinema#1]
Marquise Technologie's website has been modified, therefore the urls provided in the list are not existing anymore.

Please replace with the following urls:

**KDM Tools**
KEYMaster: [https://www.marquise-tech.com/keymaster/](https://www.marquise-tech.com/keymaster/)

**Mastering Tools**
MIST: [https://www.marquise-tech.com/mist/](https://www.marquise-tech.com/mist/)

**QC Players**
ICE Player [https://www.marquise-tech.com/ice/](https://www.marquise-tech.com/ice/)

**Transcoding Engines**
TORNADO: [https://www.marquise-tech.com/tornado/](https://www.marquise-tech.com/tornado/)

**Comment by 4lm** [comment]
Hi Laurence,

Thank you for the info! I updated the links accordingly.

It's nice to see that this list gets recognized in the industry.

Regards,
Alexis

**Comment by laurencestoll** [comment]
Thanks for the prompt reaction Alexis!!!!
